---
title: "Clustering Titles"
author: "Thao Dinh"
date: "11/13/2018"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(naniar)
library(lubridate)
```

###Create dataframe containing BOMojo Titles, IMDB Titles, and IMDB ID in prep for clustering
####Step 1: Clean IMDB Data
```{r cleanIMDB, include=FALSE}
#From the dataframe BOMojo_IMDB_small (where we have previously joined BOMojo and IMDB data by title only, allowing films with same title but distinct IMDB_ID to be duplicatedly joined to the same BOMojo title and occupy different observation rows), figure out which titles have duplicates
IMDB_frequency <- as.data.frame((table(BOMojo_IMDB_small$Title)))
IMDB_duplicates <- filter(IMDB_frequency, Freq > 1)

#Pull out the string of titles that have duplicate names
duplicate_titles <- IMDB_duplicates$Var1

#Filter out the duplicate titles from the main IMDB dataset
IMDB_without_D <- filter(IMDB_basic_subset, !(Title %in% duplicate_titles))

#I mannually cross-referened the BOMojo page for these "duplicate titles" with their various IMDB entries (using the unique IMDB_ID for each IMDB title) and isolate the IMDB_ID that correctly correspond with the BOMojo entries. 

#Pull out only the unique observations with the correct corresponding IMDB_ID to the BOMojo data entries with the same name
duplicate_title_id <- c("tt2205401", 
                        "tt5294966",
                        "tt1715336",
                        "tt3577624",
                        "tt0443465",
                        "tt1126590",
                        "tt2883434",
                        "tt1935089",
                        "tt2381111",
                        "tt2503944",
                        "tt3707106",
                        "tt3442006",
                        "tt2883512",
                        "tt3850496",
                        "tt2674454",
                        "tt2614776",
                        "tt2380307",
                        "tt3076658",
                        "tt5097070",
                        "tt4645330",
                        "tt4160708",
                        "tt4056738",
                        "tt3090634",
                        "tt3289728",
                        "tt1707380",
                        "tt4382872",
                        "tt3495026",
                        "tt4466544",
                        "tt3900206",
                        "tt3352390",
                        "tt4481414",
                        "tt5635086",
                        "tt1800302",
                        "tt5061814",
                        "tt3017412",
                        "tt5478478",
                        "tt3062096",
                        "tt2096673",
                        "tt1188982",
                        "tt2017561",
                        "tt2446980",
                        "tt2372222",
                        "tt3605418",
                        "tt3569230",
                        "tt4786282",
                        "tt3741834",
                        "tt4669986",
                        "tt2872732",
                        "tt2091935",
                        "tt4698584",
                        "tt3531824",
                        "tt2626090",
                        "tt1247690",
                        "tt1850457",
                        "tt2072233",
                        "tt2334871",
                        "tt1247690",
                        "tt4972582",
                        "tt1895587",
                        "tt4191054",
                        "tt3119416",
                        "tt3881784",
                        "tt3824458",
                        "tt3230082",
                        "tt2935564",
                        "tt1878841",
                        "tt1600196",
                        "tt3387542",
                        "tt2039393",
                        "tt2034800",
                        "tt2515034",
                        "tt4481514",
                        "tt1951181",
                        "tt4370784",
                        "tt2400463",
                        "tt4826674",
                        "tt1872194",
                        "tt4738360",
                        "tt3958072",
                        "tt1754656",
                        "tt5278832",
                        "tt5348236",
                        "tt3530002",
                        "tt4610244",
                        "tt3702652",
                        "tt3966942",
                        "tt4995790",
                        "tt1745787",
                        "tt4255304",
                        "tt3488710",
                        "tt4218696",
                        "tt3616916",
                        "tt4379728",
                        "tt4449576",
                        "tt1964418",
                        "tt1921149",
                        "tt2273657",
                        "tt3859076",
                        "tt5910280",
                        "tt2358925",
                        "tt2597892",
                        "tt2331100",
                        "tt1389139",
                        "tt1403241",
                        "tt0451279",
                        "tt3312830",
                        "tt6654316",
                        "tt1291570")

IMDB_duplicates_unique <- filter(IMDB_basic_subset, IMDB_ID %in% duplicate_title_id) 

#There was a number of films released in 2014 that IMDB reported as being released in 2013 (due to it being released on the festival circuit beforehand), and thus didn't have a match in the IMDB_basic_subset (which only contains movies from 2014-2017). I only found 3 observation of this type in the list of duplicate titles that I have isolated. 
#Create a dataframe for these 3 observations
IMDB_ID <- c("tt2017561","tt3119416", "tt1951181")
Title <- c("journey to the west", "stray dogs", "the immigrant")
Year <- c(2014, 2014, 2014)
genres <- c("Action", "Drama", "Drama")
IMDB_duplicates_extra <- data.frame(IMDB_ID, Title, Year, genres) 

#Add the now clean IMDB "duplicate titles" dataframe to the larger IMDB_subset dataset
IMDB_subset_clean <- rbind(IMDB_without_D, IMDB_duplicates_unique, IMDB_duplicates_extra)

# Add a source column
IMDB_title_clean <- IMDB_subset_clean %>%
  mutate(Source = "IMDB") %>%
  select(-1, -4)
```

####Step 2: Clean and select on Title, Year, Source
```{r cleanBOMojo, include=FALSE}
BOMojo_title_clean <- BOMojo_data_clean %>%
  #Select only Title and Year columns
  select("Title", "Year") %>%
  #Add source columns
  mutate(Source = "BOMojo")
```

####Step 3: Prep dataset containing IMDB and BOMojo titles for clustering
```{r clustering_data_IMDB_BOMojo, include=FALSE}
#join IMDB_title_clean and BOMojo_title_clean together, keeping all observations that didn't join
BOMojo_IMDB_title <- merge(IMDB_title_clean, BOMojo_title_clean, by = c("Title"), all = TRUE)

#Filter out all of the observations that did match, leaving only observation with no match
BOMojo_IMDB_title_subset <- BOMojo_IMDB_title %>%
  filter(is.na(Source.x) | is.na(Source.y)) %>%
  #gather the Source.x/Source.y columns into Source
  gather(key = Dataset, value = Source, Source.x, Source.y) %>%
  #gather the Year.x/Year.y columns into Year
  gather(key = DS, value = Year, Year.x, Year.y) %>%
  #drop the NA introduced due to using the gather() function
  drop_na() %>%
  #select Title, Year, Source columns only
  select(Title, Year, Source) %>%
  #arange data to have IMDB data up top and BOMojo at the bottom
  arrange(desc(Source)) %>%
  #duplicate title column
  mutate(Title2 = Title)

#Export BOMojo_IMDB_title dataset
write.csv(BOMojo_IMDB_title_subset, file = "Clustering slightly different BOMojo and IMDB Titles.csv", quote = TRUE, row.names = FALSE)
```

####Step 4: Seperate BOMojo_IMDB_title_subset out by year
```{r byyear, include=FALSE}
#Import file I was working on in OpenRefine (and in which I has merged some titles) before deciding to switch over to new method
BOMojo_IMDB_title_subset_111618 <- read_csv("Clustering-slightly-different-BOMojo-and-IMDB-Titles-111618-csv.csv")

has_been_merged <- BOMojo_IMDB_title_subset_111618 %>%
  filter(Source == "BOMojo") %>%
  filter(Title != Title2)

merged_title <- has_been_merged$Title2

BOMojo_IMDB_title_subset_111618_new <- BOMojo_IMDB_title_subset_111618 %>%
  filter(!(Title2 %in% merged_title))

BOMojo_IMDB_title_unmerged_2014 <- filter(BOMojo_IMDB_title_subset_111618_new, Year == 2014) 

#Export BOMojo_IMDB_title_unmerged_2014 dataset for clustering purpose
write.csv(BOMojo_IMDB_title_unmerged_2014, file = "Clustering BOMojo and IMDB Titles 2014.csv", quote = TRUE, row.names = FALSE)

#filter and export a dataset containing unmeerged 2015 titles for Clustering purpose
BOMojo_IMDB_title_unmerged_2015 <- filter(BOMojo_IMDB_title_subset_111618_new, Year == 2015)
write.csv(BOMojo_IMDB_title_unmerged_2015, file = "Clustering BOMojo and IMDB Titles 2015.csv", quote = TRUE, row.names = FALSE)

#filter and export a dataset containing unmeerged 2016 titles for Clustering purpose
BOMojo_IMDB_title_unmerged_2016 <- filter(BOMojo_IMDB_title_subset_111618_new, Year == 2016)
write.csv(BOMojo_IMDB_title_unmerged_2016, file = "Clustering BOMojo and IMDB Titles 2016.csv", quote = TRUE, row.names = FALSE)

#filter and export a dataset containing unmeerged 2017 titles for Clustering purpose
BOMojo_IMDB_title_unmerged_2017 <- filter(BOMojo_IMDB_title_subset_111618_new, Year == 2017)
write.csv(BOMojo_IMDB_title_unmerged_2017, file = "Clustering BOMojo and IMDB Titles 2017.csv", quote = TRUE, row.names = FALSE)
```

####Step 5: reimport and replace BOMojo titles with IMDB titles after the clustering process
```{r afterclustering, include=FALSE}
#Import dataset of 2014 BOMojo and IMDB titles that has been clustered and edited
BOMojo_IMDB_clustered_2014 <- read_csv("Clustering-BOMojo-and-IMDB-Titles-2014-csv.csv")

BOMojo_IMDB_clustered_2014 <- BOMojo_IMDB_clustered_2014 %>%
  filter(Source == "BOMojo")

#Import dataset of 2015 BOMojo and IMDB titles that has been clustered
BOMojo_IMDB_clustered_2015 <- read_csv("Clustering-BOMojo-and-IMDB-Titles-2015-csv.csv")

BOMojo_IMDB_clustered_2015 <- BOMojo_IMDB_clustered_2015 %>%
  filter(Source == "BOMojo")

#Import dataset of 2016 BOMojo and IMDB titles that has been clustered
BOMojo_IMDB_clustered_2016 <- read_csv("Clustering-BOMojo-and-IMDB-Titles-2016-csv.csv")

BOMojo_IMDB_clustered_2016 <- BOMojo_IMDB_clustered_2016 %>%
  filter(Source == "BOMojo")

#Import dataset of 2017 BOMojo and IMDB titles that has been clustered
BOMojo_IMDB_clustered_2017 <- read_csv("Clustering-BOMojo-and-IMDB-Titles-2017-csv.csv")

BOMojo_IMDB_clustered_2017 <- BOMojo_IMDB_clustered_2017 %>%
  filter(Source == "BOMojo")

#Bind the clean BOMojo titles for all 4 years together
BOMojo_IMDB_edited <- rbind(BOMojo_IMDB_clustered_2014, BOMojo_IMDB_clustered_2015, BOMojo_IMDB_clustered_2016, BOMojo_IMDB_clustered_2017)


#Reattach IMDB_ID and Genre to the BOMojo_IMDB_edited titles using the new IMDB_compliant names
BOMojo_IMDB_edited <- merge(BOMojo_IMDB_edited, IMDB_subset_clean, by.x = c("Title2", "Year"), by.y = c("Title", "Year"), all.x = TRUE, all.y = FALSE)

#Remove the unintended duplicates (resulting from 2 or more titles of the same name being released in the same year)
Frequency2 <- as.data.frame((table(BOMojo_IMDB_edited$Title2)))
Frequency2 <- filter(Frequency2, Freq > 1)
#Use the list of titles from Frequency2 to identify the correct IMDB_ID
#Filter out the rest
wrong_dupl <- c("tt4226970", "tt5884960", "tt5121236", "tt6954894", "tt2943946", "tt7913816", "tt5089556", "tt5112932", "tt3985956", "tt4594050", "tt3532296", "tt3614128", "tt8212482", "tt2570574", "tt3660078", "tt3308106", "tt7232438", "tt4192918", "tt4979652")
BOMojo_IMDB_edited <- filter(BOMojo_IMDB_edited, !(IMDB_ID %in% wrong_dupl))
BOMojo_IMDB_edited <- select(BOMojo_IMDB_edited, -4)

#For the remaining unmatched observations, match with the list I have created of film titles where the BOMojo and IMDB year doesn't match
BOMojo_IMDB_edited1 <- BOMojo_IMDB_edited %>%
  filter(is.na(IMDB_ID)) %>%
  select(-4, -5)
BOMojo_IMDB_edited1 <- merge(BOMojo_IMDB_edited1, Fill_in_IMDB_data, by.x = c("Title2", "Year"), by.y = c("Title", "BOMojo year"), all.x = TRUE, all.y = FALSE)

#Identify the remaining unmatched observations and match with the larger IMDB frame without constraining it by year
BOMojo_IMDB_edited2 <- BOMojo_IMDB_edited1 %>%
  filter(is.na(IMDB_ID)) %>%
  select(-4, -5)

BOMojo_IMDB_edited2 <- merge(BOMojo_IMDB_edited2, IMDB_subset_clean, by.x = c("Title2"), by.y = c("Title"), all.x = TRUE, all.y = FALSE)
BOMojo_IMDB_edited2 <- BOMojo_IMDB_edited2%>%
  select(-5) %>%
  #rename Year.x to Year
  rename("Year" = Year.x)


#Issue: some titles don't join no matter what I do, even when the title is exact
#For the remaining unmatched observations that STILL doesn't join, handcompute.
BOMojo_IMDB_edited3 <- read_csv("Manual BOMojo-IMDB Join.csv")

#Join BOMojo_IMDB_edited, BOMojo_IMDB_edited1, BOMojo_IMDB_edited2 and BOMojo_IMDB_edited3, then drop NA (most NA in BOMojo_IMDB_edited should have been filled in by 1, 2 and 3)
#Check: number of observations under BOMojo_IMDB_edited = # observations under new dataframe
#Note: there will be slight differences because I have removed the reissued titles when manually computing BOMojo_IMDB_edited3
BOMojo_IMDB_edited_final <- rbind(BOMojo_IMDB_edited, BOMojo_IMDB_edited1, BOMojo_IMDB_edited2, BOMojo_IMDB_edited3)

BOMojo_IMDB_edited_final <- drop_na(BOMojo_IMDB_edited_final)

#
has_been_merged_wIMDB_ID <- merge(has_been_merged, IMDB_subset_clean, by.x = c("Title2", "Year"), by.y = c("Title", "Year"), all = FALSE)
has_been_merged_wIMDB_ID <- select(has_been_merged_wIMDB_ID, -4)

BOMojo_title_clean1 <- BOMojo_title_clean %>%
  select(-3) %>%
  mutate(Title2 = Title) 
BOMojo_IMDB_join <- merge(BOMojo_title_clean1, IMDB_subset_clean, by = c("Title", "Year"), all.x = TRUE, all.y = FALSE)
BOMojo_IMDB_cleanjoin <- BOMojo_IMDB_join %>%
  drop_na()

BOMojo_IMDB_final <- rbind(BOMojo_IMDB_edited_final, has_been_merged_wIMDB_ID, BOMojo_IMDB_cleanjoin)

#Issue: the number of obervations in BOMojo_IMDB_final and BOMojo_IMDB_cleanjoin differs, suggesting that there are still observations in BOMojo observations that didn't have IMDB title attached. 
#Identify and seperate them out into seperate dataframe
BOMojo_IMDB_final_OGtitle <- BOMojo_IMDB_final$Title
BOMojo_IMDB_unmatched <- BOMojo_IMDB_join %>%
  filter(is.na(IMDB_ID)) %>%
  filter(!(Title %in% BOMojo_IMDB_final_OGtitle))

#Solution 1: not constraint merge by Year
BOMojo_IMDB_unmatched_sol1 <- merge(BOMojo_IMDB_unmatched, IMDB_subset_clean, by = c("Title"), all.x = TRUE, all.y = FALSE)
BOMojo_IMDB_cleanjoin1 <- BOMojo_IMDB_unmatched_sol1 %>%
  filter(!is.na(IMDB_ID.y)) %>%
  select(-4, -5, -7) %>%
  rename("Year" = Year.x, "IMDB_ID" = IMDB_ID.y, "genres" = genres.y)

#Rejoin BOMojo_IMDB_cleanjoin1 to BOMojo_IMDB_final
BOMojo_IMDB_final1 <- rbind(BOMojo_IMDB_final, BOMojo_IMDB_cleanjoin1)  
#Note: there will be slight differences between #observations in  BOMojo_IMDB_final1 and BOMojo_data_clean because I have removed the reissued titles
BOMojo_IMDB_final1 <- rename(BOMojo_IMDB_final1, "IMDB_Title" = Title2)
```


